### ISSUE TITLE
FileNotFoundError for datasets/MultiTQ/kg/full.txt

### ISSUE THREAD

**Issue by wll-best** [qianxinying/TimeR4#2]
Hello, thank you for your great work on this project! I encountered an issue while running Step 1 of the inference process.

I executed the following command:
python main.py --output_path datasets/MultiTQ/results/test_prompt.json --question_path datasets/MultiTQ/questions/test.json --retrieve_name models/multi_model --triplet_path datasets/MultiTQ/kg/full.txt

However, I received the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MultiTQ/kg/full.txt'

Could you provide guidance on how to resolve this issue?
Thank you for your help!

**Comment by qianxinying** [comment]
Thank you for your suggestion. We have uploaded the full.txt file.

**Comment by wll-best** [comment]
Thank you!
